id = "openai/gpt-5" # required field, all the rest are optional. "omit if not sure" means to omit a key if we cant extrapolate a value from the provider's documentation or api.
knowledge_cutoff = "1777663364" # unix timestamp, omit if not sure
last_updated = "1777663364" # unix timestamp, omit if not sure
name = "GPT 5.0"
open_weights = false # true|false, omit if not sure
release_date = "1777663364" # unix timestamp, omit if not sure

[features] # supported features, true|false, omit if not sure for each feature
attachment = true
reasoning = true
structured_output = true
temperature = true
tool_call = true

[limit] # limits, omit if not sure for each limit category
context = 400_000 # max context window size
input = 272_000 # max input tokens per request
output = 8_192 # max output tokens per response

[modalities] # modalities, omit if not sure for each modality category
input = ["text", "image"] # could be text, image, audio, video, file
output = ["text"] # could be text, image, audio, video, file

[pricing] # per million tokens, USD. number, omit if not sure for each pricing category
cache_read = 0.30
cache_write = 3.75
input = 3.00
input_audio = 1.00
output = 15.00
output_audio = 10.00
reasoning = 15.00
